name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Получаем код из GitHub
        uses: actions/checkout@v3

      - name: Устанавливаем SSH-ключ
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > aws_key.pub
          chmod 600 aws_key.pub

      - name: Деплой на сервер
        run: |
          ssh -i aws_key.pem -o StrictHostKeyChecking=no ubuntu@13.48.135.188 <<EOF
            cd /home/ubuntu/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
