name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Получаем код из GitHub
        uses: actions/checkout@v3

      - name: Save SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > eleganza_db_SSH_key.pem
          chmod 400 eleganza_db_SSH_key.pem

      - name: Деплой на сервер
        run: |
            ssh -i eleganza_db_SSH_key.pem -o StrictHostKeyChecking=no ubuntu@13.62.1.39 << 'EOF'
              cd /home/ubuntu/Eleganza
              git pull origin main
              docker-compose down
              docker-compose up --build -d
            EOF
        
        

