name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Получаем код из GitHub
        uses: actions/checkout@v3

      - name: Save SSH key
        run: |
             echo "${{ secrets.AWS_SSH_KEY }}" > Eleganza.pem
              chmod 400 Eleganza.pem
              ssh -i Eleganza.pem -o StrictHostKeyChecking=no ubuntu@13.48.135.188 <<EOF
                cd /home/ubuntu/project
                git pull origin main
                docker-compose down
                docker-compose up --build -d
              EOF

      


      - name: Деплой на сервер
        run: |
          ssh -i aws_key.pem -o StrictHostKeyChecking=no ubuntu@13.48.135.188 <<EOF
            cd /home/ubuntu/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
